#
# TA-protectornet - ProtectorNet Technology Add-on for Splunk
#
# Copyright (C) 2026 ProtectorNet Pty Ltd. All rights reserved.
#

[install]
is_configured = false
build = 1

[ui]
is_visible = true
label = ProtectorNet
docs_section_override = AddOns:released

[launcher]
author = ProtectorNet Pty Ltd
description = Enrich Splunk events with ProtectorNet threat intelligence. Custom search commands, adaptive response actions, and workflow actions for URL/domain threat analysis using ProtectorNet WebScan and ThreatHunt services.
version = 1.0.0

[package]
id = TA-protectornet
check_for_updates = true
