#
# commands.conf — Custom search command definitions
#

[protectornetscan]
filename = protectornetscan.py
chunked = true
python.version = python3

[protectornetstatus]
filename = protectornetstatus.py
chunked = true
python.version = python3

[protectornetverdict]
filename = protectornetverdict.py
chunked = true
python.version = python3
