#
# workflow_actions.conf — Right-click workflow actions in Splunk events
#

[protectornet_scan_url]
display_location = both
fields = url, dest_url, src_url, http_referrer, uri
label = Scan with ProtectorNet
link.method = get
link.target = blank
link.uri = /app/TA-protectornet/protectornet_overview?url=$!url$
type = link

[protectornet_scan_domain]
display_location = both
fields = domain, dest_host, src_host, dns_query
label = Scan Domain with ProtectorNet
link.method = get
link.target = blank
link.uri = /app/TA-protectornet/protectornet_overview?url=https://$!domain$
type = link
